config/routes.rb
# == Route Map
#
#          Prefix Verb   URI Pattern                   Controller#Action
#       questions GET    /questions(.:format)          questions#index
#                 POST   /questions(.:format)          questions#create
#    new_question GET    /questions/new(.:format)      questions#new
#   edit_question GET    /questions/:id/edit(.:format) questions#edit
#        question GET    /questions/:id(.:format)      questions#show
#                 PATCH  /questions/:id(.:format)      questions#update
#                 PUT    /questions/:id(.:format)      questions#update
#                 DELETE /questions/:id(.:format)      questions#destroy
# questions_index GET    /questions/index(.:format)    questions#index
#

Rails.application.routes.draw do
#  root to: 'sessions#new'
#  resource :session, only: [:new, :create, :destroy]

  resources :questions
  get 'questions/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order("body").page(params[:page]).per(5)

  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def update
  end

  def destroy
  end
  
  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
 end

 def create
   user = User.find_by_email(params[:email])

   if user && user.authenticate(params[:password])
     session[:user_id] = user.id
     redirect_to root_path
   else
     redirect_to new_session_path
   end
 end

 def destroy
   session[:user_id] = nil
   redirect_to new_session_path
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quests</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/index.html.erb
<%= paginate @questions =%>

<h1>Listing questions</h1>
<%= link_to 'New question', new_question_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <td><%= question.body %></td>
      <td><%= link_to 'Show', question_path(question) %></td>
    </tr>
  <% end %>
</table>

app/views/questions/login.html.erb
<h1>Login</h1>

<% if current_user %>
  You are now logged in as: <%= current_user.email %>.
  <%= link_to "Log out", session_path, method: :destroy %>.
<% else %>
  You are not logged in.
<% end %>

<%= form_tag session_path do %>
  Email: <%= text_field_tag :email %>
  Password: <%= password_field_tag :password %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/questions/new.html.erb
<%= form_for :question, url: questions_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <%= link_to 'Back', questions_path %>
<% end %>

app/views/questions/show.html.erb
<%= paginate @questions =%>
<p>
  <%= link_to 'New question', new_question_path %>
  <br>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>